server:
  port: 8885

springdoc:
  show-actuator: true

management:
  server:
    port: 8888
  health:
    status:
      http-mapping:
        up: 200
        down: 400
  endpoint:
    restart:
      enabled: true
    health:
      show-details: "ALWAYS"
  security:
    enabled: false
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
    enabled-by-default: true
  info:
    git:
      mode: full
  metrics:
    export:
      newrelic:
        enabled: false

spring:
  application:
    name: omsapigatewaywebflux
  jmx:
    enabled: false
  jackson:
    default-property-inclusion: non_null
  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://kckdev.raiadrogasil.com.br/auth/realms/OMS
          jwk-set-uri: https://kckdev.raiadrogasil.com.br/auth/realms/OMS/protocol/openid-connect/certs

  cloud:
    kubernetes:
      enabled: true
      secrets:
        enable-api: true
        namespace: SPR_APP_NAME-secret
      reload:
        enabled: false

    gateway:
      metrics:
        enabled: true
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true

      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: http://localhost:4200
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
      routes:
        - id: token-service
          uri: http://localhost:8887/api/v1/authbase/token
          order: 1
          predicates:
            - Path=/api/v1/{api}/oauth2/token
          filters:
            - PreserveHostHeader
            - SaveSession
            - SetPath=/api/v1/authbase/token

        - id: bff-oms
          uri: http://bffoms-dev:8887/api/v1/oms
          order: 10
          predicates:
            - Path=/api/v1/oms/**

kong:
  host: oms-dev.rd.com.br


springfox:
  documentation:
    swagger:
      v2:
        home: /docs
        contactEmail: desenvolvimento_oms@rd.com.br


apigateway:
  security:
    configs:
      pathMatchers:
        -
          urlPattern: '/*/*/*/oauth2/token'
          permitAll: true
        -
          urlPattern: '/actuator/**'
          permitAll: true
        -
          urlPattern: "/*/*/oms/**"
          roles:
            - uma_protection
            - role-apigateway
            - uma_authorization
            - "ADM DO SISTEMA"
      anyExchange:
        roles:
          - role_user_poc
log:
  level: INFO

logging:
  level:
    root: ${log.level}
    org:
      springframework: ${log.level}
    br:
      com:
        rd: ${log.level}
    com:
      rd: ${log.level}

