server:
  port: 8885

keycloak-detail: /realms/eselwer/.well-known/openid-configuration

identity-provider:
  address: ${KEYCLOAK_ADDRESS:192.168.39.186:30800}
  helm: eselwer

springdoc:
  show-actuator: true

management:
  server:
    port: 8888
    base-path: /health
  health:
    status:
      http-mapping:
        up: 200
        down: 400
  endpoint:
    restart:
      enabled: true
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
    enabled-by-default: true
  info:
    git:
      mode: full

spring:
  application:
    name: apigateway
  jmx:
    enabled: false
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: ${PROFILE:dev}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${identity-provider.address}/realms/${identity-provider.helm}
          jwk-set-uri: http://${identity-provider.address}/realms/${identity-provider.helm}/protocol/openid-connect/certs

  cloud:
    gateway:
      metrics:
        enabled: true
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true

      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "http://localhost:4200, http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
      routes:
        - id: token-service
          uri: http://localhost:8887
          order: 1
          predicates:
            - Path=/authentication/v1/identifications/{action}
          filters:
            - PreserveHostHeader
            - SaveSession
            - SetPath=/api/v1/authbase/{action}

        - id: session-service
          uri: http://localhost:8887
          order: 2
          predicates:
            - Path=/authentication/v1/sessions
          filters:
            - PreserveHostHeader
            - SaveSession
            - SetPath=/api/v1/authbase/sessions


        - id: bff-oms
          uri: http://192.168.39.15:32699
          order: 10
          predicates:
            - Path=/api/v1/oms/**
          filters:
            - SetPath=/realms/eselwer/.well-known/openid-configuration

apigateway:
  security:
    configs:
      pathMatchers:
        -
          urlPattern: '/authentication/v1/identifications/**'
          permitAll: true
        -
          urlPattern: '/actuator/**'
          permitAll: true

        - method: OPTIONS
          urlPattern: "/authentication/v1/sessions"
          permitAll: true
        -
          urlPattern: "/authentication/v1/sessions"
          roles:
            - uma_protection
            - role-apigateway
            - uma_authorization
            - "ADM DO SISTEMA"


        -
          urlPattern: "/*/*/oms/**"
          roles:
            - uma_protection
            - role-apigateway
            - uma_authorization
            - "ADM DO SISTEMA"
      anyExchange:
        roles:
          - role_user_poc
log:
  level: INFO

logging:
  level:
    root: ${log.level}
    org:
      springframework: ${log.level}
    br:
      com:
        rd: ${log.level}
    com:
      rd: ${log.level}

