server:
  port: ${PORT:8885}
  max-http-request-header-size: 168192

search-domain-api: ${SEARCH_DOMAIN_ADDRESS:localhost:8887}
auth-base-api: ${AUTH_BASE_ADDRESS:localhost:8887}
account-api: ${ACCOUNT_ADDRESS:localhost:8888}

identity-provider:
  address: ${KEYCLOAK_ADDRESS:192.168.15.103:31895}
  helm: ${KEYCLOAK_HELM:feriaz}

keycloak-detail: /realms/${identity-provider.helm}/.well-known/openid-configuration

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /_app-state
  endpoint:
    health:
      show-details: always
      probes:
        add-additional-paths: true
        enabled: true

spring:
  application:
    name: apigateway
  jmx:
    enabled: false
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: ${PROFILE:dev}

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://${identity-provider.address}/realms/${identity-provider.helm}
      resourceserver:
        jwt:
          issuer-uri: http://${identity-provider.address}/realms/${identity-provider.helm}
          jwk-set-uri: http://${identity-provider.address}/realms/${identity-provider.helm}/protocol/openid-connect/certs

  cloud:
    gateway:
      metrics:
        enabled: true
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true

      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: ${GATEWAY_ALLOW_ORING:http://poc-eselwer.sytes.net:3000, http://localhost:3000}
            allowedHeaders: "*"
            maxAge: 30
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS

      routes:
        - id: token-service
          uri: http://${auth-base-api}
          order: 1000
          predicates:
            - Path=/authentication/v1/identifications/{action}
          filters:
            - SetPath=/authbase/{action}
            - RemoveRequestHeader=X-Forwarded
            - RemoveRequestHeader=X-Forwarded-Host
            - RemoveRequestHeader=X-Forwarded-Port
            - SetRequestHeader=X-Forwarded, ${identity-provider.address}
            - SetRequestHeader=X-Forwarded-Host, ${identity-provider.address}
            - SetRequestHeader=X-Forwarded-Port, 9776
            - PreserveHostHeader

        - id: session-service
          uri: http://${auth-base-api}
          order: 1500
          predicates:
            - Path=/authentication/v1/sessions
          filters:
            - PreserveHostHeader
            - SaveSession
            - SetPath=/authbase/sessions

        - id: user-access
          uri: http://${auth-base-api}
          order: 1700
          predicates:
            - Path=/access/v1/users/**
          filters:
            - PreserveHostHeader
            - SaveSession
            - RewritePath=/access/v1/users, /users

        - id: account-api
          uri: http://${account-api}
          order: 2000
          predicates:
            - Path=/manager/v1/accounts/**
          filters:
            - PreserveHostHeader
            - SaveSession
            - RewritePath=/manager/v1/accounts, /accounts

        - id: search-domain-api
          uri: http://${search-domain-api}
          order: 2500
          predicates:
            - Path=/domains/v1/searchs/**
          filters:
            - PreserveHostHeader
            - SaveSession
            - RewritePath=/domains/v1/searchs, /searchs-domains



apigateway:
  security:
    configs:
      pathMatchers:
        - method: GET
          urlPattern: "/_app-state/health"
          permitAll: true

        -
          urlPattern: '/authentication/v1/identifications/**'
          permitAll: true


        - method: OPTIONS
          urlPattern: "/**"
          permitAll: true

        -
          urlPattern: "/authentication/v1/identities-providers/**"
          roles:
            - uma_protection
            - role-apigateway
            - uma_authorization
            - "ADM DO SISTEMA"

        -
          urlPattern: "/authentication/v1/sessions"
          roles:
            - uma_protection
            - role-apigateway
            - uma_authorization
            - "ADM DO SISTEMA"

        -
          urlPattern: "/access/**"
          roles:
            - uma_protection
            - role-apigateway
            - uma_authorization
            - "ADM DO SISTEMA"


        -
          urlPattern: "/manager/**"
          roles:
            - uma_protection
            - role-apigateway
            - uma_authorization
            - "ADM DO SISTEMA"

        -
          urlPattern: "/domains/**"
          roles:
            - uma_protection
            - role-apigateway
            - uma_authorization
            - "ADM DO SISTEMA"

      anyExchange:
        roles:
          - role_user_poc
log:
  level: ${LOG_LEVEL:DEBUG}

logging:
  level:
    root: ${log.level}
    org:
      springframework: ${log.level}
    br:
      com:
        rd: ${log.level}
    com:
      rd: ${log.level}

