spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://kckdev.raiadrogasil.com.br/auth/realms/OMS
          jwk-set-uri: https://kckdev.raiadrogasil.com.br/auth/realms/OMS/protocol/openid-connect/certs
  main:
    web-application-type: reactive
  jmx:
    enabled: true

  cloud:
    gateway:
      routes:
        - id: stock-service
          uri: http://localhost:8888/v1/api/stocks
          order: 10
          predicates:
            - Path=/v1/api/stocks/**

        - id: token-service
          uri: http://localhost:8887/v1/api/authbase/token
          order: 1
          predicates:
            - Path=/v1/api/{api}/oauth2/token
          filters:
            - PreserveHostHeader
            - SaveSession
            - SetPath=/v1/api/authbase/token

logging:
  level: "info"
  org:
    springframework:
      security: DEBUG

keycloak:
  use-resource-role-mappings: 'true'

apigateway:
  security:
    configs:
      pathMatchers:
        -
          method: POST
          patterns: "/*/*/*/oauth2/token"
          roles:
            - admin
            - teste

        - method: GET
          patterns: '/*/*/*/oauth2/token'
          permitAll: false
          roles:
            - admin
            - teste

        -
            patterns: '/*/*/*/oauth2/token/teste'
            roles:
              - admin
              - teste

      anyExchange:
        roles:
          - admin
          - teste

