server:
  port: 8082

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  security:
    enabled: false
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"

spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://kckdev.raiadrogasil.com.br/auth/realms/OMS
          jwk-set-uri: https://kckdev.raiadrogasil.com.br/auth/realms/OMS/protocol/openid-connect/certs
  main:
    web-application-type: reactive
  jmx:
    enabled: true
  cloud:
    kubernetes:
      enabled: true

    gateway:
      httpclient:
        wiretap: true
      httpserver:
          wiretap: true
      metrics:
        enabled: true
      routes:
        - id: stock-service
          uri: http://localhost:8888/v1/api/stocks
          order: 10
          predicates:
            - Path=/v1/api/stocks/**

        - id: token-service
          uri: http://localhost:8887/v1/api/authbase/token
          order: 1
          predicates:
            - Path=/v1/api/{api}/oauth2/token
          filters:
            - PreserveHostHeader
            - SaveSession
            - SetPath=/v1/api/authbase/token


apigateway:
  security:
    configs:
      pathMatchers:
        - method: POST
          urlPattern: '/*/*/*/oauth2/token'
          permitAll: true

        -
          urlPattern: '/actuator/**'
          permitAll: true

        - method: POST
          urlPattern: "/*/*/stocks/*"
          roles:
            - role-apigateway

      anyExchange:
        roles:
          - role_user_poc

logging:
  level:
    org:
      springframework: INFO